### ISSUE TITLE
Support new linalg algorithms

### ISSUE THREAD

**Issue by YuhanLiin** [rust-ml/ndarray-linalg-rs#3]
- [x] SVD
- [x] LOBPCG (might not be needed, since most use cases of this are covered by SVD and `eigh`)
- [x] Matrix inverse
- [x] Least Squares

The interface and behaviour of the API should follow that of `ndarray-linalg`. `nalgebra` is a good reference for the implementation.

**Comment by bytesnake** [comment]
supports the SVD routine also non-complete decompositions for very large matrix systems?

**Comment by bytesnake** [comment]
it may make sense to have two libraries, one for traditional decompositions based on givens rotation/householder and another one for iterative methods like power method, conjugate gradient methods, LOBPCG etc.

**Comment by YuhanLiin** [comment]
I'm not sure about splitting into 2 crates, since I want to share this crate's underlying machinery for errors and testing across all algorithms. However we definitely need something like LOBPCG for truncated SVD. The problem is I don't know how to implement it, since it's not part of `nalgebra`.

**Comment by bytesnake** [comment]
yeah two modules would also suffice. LOBPCG just uses a closed eigenvalue decomposition routine, it should be relatively straightforward to port it from `ndarray-linalg` to this
